import { NextResponse } from "next/server";

export const blogs = [
  {
    id: 27,
    title: "WebSockets in Real-time Apps",
    content: "Implementing real-time communication with WebSockets.",
    thumbnail: "https://picsum.photos/200/300?random=25",
    isFeatured: true,
    tags: ["websockets", "realtime", "app"],
    views: 0,
    authorId: 1,
    createdAt: "2025-09-18T17:11:24.147Z",
    updatedAt: "2025-09-18T17:11:24.147Z",
    author: {
      id: 1,
      name: "anika",
      email: "anika@gmail.com",
      phone: "01234567890",
      picture: null,
      role: "USER",
      status: "ACTIVE",
    },
  },
  {
    id: 26,
    title: "Exploring Serverless Functions",
    content: "A beginner’s guide to serverless architecture and functions.",
    thumbnail: "https://picsum.photos/200/300?random=24",
    isFeatured: false,
    tags: ["serverless", "functions", "cloud"],
    views: 0,
    authorId: 4,
    createdAt: "2025-09-18T17:11:14.788Z",
    updatedAt: "2025-09-18T17:11:14.788Z",
    author: {
      id: 4,
      name: "nishat",
      email: "nishat@gmail.com",
      phone: "01234567890",
      picture: null,
      role: "USER",
      status: "ACTIVE",
    },
  },
  {
    id: 25,
    title: "Using MongoDB with Node.js",
    content: "Learn how to integrate MongoDB into Node.js projects.",
    thumbnail: "https://picsum.photos/200/300?random=23",
    isFeatured: true,
    tags: ["mongodb", "database", "node"],
    views: 0,
    authorId: 3,
    createdAt: "2025-09-18T17:11:06.997Z",
    updatedAt: "2025-09-18T17:11:06.997Z",
    author: {
      id: 3,
      name: "jumana",
      email: "jumana@gmail.com",
      phone: "01234567890",
      picture: null,
      role: "USER",
      status: "ACTIVE",
    },
  },
  {
    id: 24,
    title: "Building a Blog with Next.js",
    content: "Step-by-step tutorial for creating a blog with Next.js.",
    thumbnail: "https://picsum.photos/200/300?random=22",
    isFeatured: false,
    tags: ["next", "blog", "web"],
    views: 0,
    authorId: 2,
    createdAt: "2025-09-18T17:10:58.293Z",
    updatedAt: "2025-09-18T17:10:58.293Z",
    author: {
      id: 2,
      name: "khanam",
      email: "khanam@gmail.com",
      phone: "01234567890",
      picture: null,
      role: "USER",
      status: "ACTIVE",
    },
  },
  {
    id: 23,
    title: "Understanding Async/Await",
    content: "Async/Await makes handling promises much easier in JS.",
    thumbnail: "https://picsum.photos/200/300?random=21",
    isFeatured: true,
    tags: ["javascript", "async", "promises"],
    views: 0,
    authorId: 1,
    createdAt: "2025-09-18T17:10:48.847Z",
    updatedAt: "2025-09-18T17:10:48.847Z",
    author: {
      id: 1,
      name: "anika",
      email: "anika@gmail.com",
      phone: "01234567890",
      picture: null,
      role: "USER",
      status: "ACTIVE",
    },
  },
  {
    id: 22,
    title: "Cloud Hosting on AWS",
    content: "Learn how to deploy applications on AWS cloud.",
    thumbnail: "https://picsum.photos/200/300?random=20",
    isFeatured: false,
    tags: ["aws", "cloud", "hosting"],
    views: 0,
    authorId: 4,
    createdAt: "2025-09-18T17:10:41.598Z",
    updatedAt: "2025-09-18T17:10:41.598Z",
    author: {
      id: 4,
      name: "nishat",
      email: "nishat@gmail.com",
      phone: "01234567890",
      picture: null,
      role: "USER",
      status: "ACTIVE",
    },
  },
  {
    id: 21,
    title: "CI/CD with GitHub Actions",
    content: "Automating deployment pipelines using GitHub Actions.",
    thumbnail: "https://picsum.photos/200/300?random=19",
    isFeatured: true,
    tags: ["cicd", "github", "devops"],
    views: 0,
    authorId: 3,
    createdAt: "2025-09-18T17:10:34.430Z",
    updatedAt: "2025-09-18T17:10:34.430Z",
    author: {
      id: 3,
      name: "jumana",
      email: "jumana@gmail.com",
      phone: "01234567890",
      picture: null,
      role: "USER",
      status: "ACTIVE",
    },
  },
  {
    id: 20,
    title: "Unit Testing with Jest",
    content: "Learn how to write effective unit tests using Jest.",
    thumbnail: "https://picsum.photos/200/300?random=18",
    isFeatured: false,
    tags: ["testing", "jest", "javascript"],
    views: 0,
    authorId: 2,
    createdAt: "2025-09-18T17:10:26.791Z",
    updatedAt: "2025-09-18T17:10:26.791Z",
    author: {
      id: 2,
      name: "khanam",
      email: "khanam@gmail.com",
      phone: "01234567890",
      picture: null,
      role: "USER",
      status: "ACTIVE",
    },
  },
  {
    id: 19,
    title: "Next.js App Router Deep Dive",
    content: "Everything you need to know about the Next.js App Router.",
    thumbnail: "https://picsum.photos/200/300?random=17",
    isFeatured: true,
    tags: ["next", "router", "web"],
    views: 0,
    authorId: 1,
    createdAt: "2025-09-18T17:10:17.951Z",
    updatedAt: "2025-09-18T17:10:17.951Z",
    author: {
      id: 1,
      name: "anika",
      email: "anika@gmail.com",
      phone: "01234567890",
      picture: null,
      role: "USER",
      status: "ACTIVE",
    },
  },
  {
    id: 18,
    title: "UI Components with ShadCN",
    content: "Beautiful and customizable UI components with ShadCN.",
    thumbnail: "https://picsum.photos/200/300?random=16",
    isFeatured: false,
    tags: ["ui", "shadcn", "design"],
    views: 0,
    authorId: 4,
    createdAt: "2025-09-18T17:10:09.325Z",
    updatedAt: "2025-09-18T17:10:09.325Z",
    author: {
      id: 4,
      name: "nishat",
      email: "nishat@gmail.com",
      phone: "01234567890",
      picture: null,
      role: "USER",
      status: "ACTIVE",
    },
  },
];

export async function GET() {
  return Response.json(blogs);
}

export const POST = async (request: Request) => {
  const blog = await request.json();
  const newBlog = {
    ...blog,
    id: blogs.length + 1,
  };
  blogs.push(newBlog);

  return new NextResponse(JSON.stringify(newBlog), {
    status: 201,
    headers: {
      "Content-type": "application/json",
    },
  });
};
